---

- name: Install opensearch_extra_packages
  yum:
    name: "{{ opensearch_extra_packages }}"
    state: present

- name: Install opensearch_package
  yum:
    name: "{{ opensearch_package }}"
    state: present

- name: Create /etc/sysconfig/opensearch
  template:
    src: RedHat.sysconfig.j2
    dest: /etc/sysconfig/opensearch
    owner: root
    group: root
    mode: 0644
    validate: sh -n %s
